name: Release Please

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: github.event.pull_request.merged == true # Only run when a PR is merged
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          target-branch: dev
          skip-github-pull-request: true
